version: '2'

services:
  server1:
    build:
      context:  ./Web-Apache2
      dockerfile: Dockerfile
    environment:
      - id_server=1
    volumes:
      - apache_volume1:/usr/local/apache2/htdocs/

  server2:
    build:
      context:  ./Web-Apache2
      dockerfile: Dockerfile
    environment:
       - id_server=2
    volumes:
       - apache_volume2:/usr/local/apache2/htdocs/

  server3:
    build:
      context:  ./Web-Apache2
      dockerfile: Dockerfile
    environment:
      - id_server=3
    volumes:
      - apache_volume3:/usr/local/apache2/htdocs/

  nginx:
    build:
      context:  ./Nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - nginx_volume:/etc/nginx/

volumes:
    apache_volume1:
    apache_volume2:
    apache_volume3:
    nginx_volume:
